### ISSUE TITLE
点击首页问题列表item， 报thirdScriptError

### ISSUE THREAD

**Issue by W-quan** [NervJS/taro-zhihu-sample#14]
```
VM152:1 thirdScriptError
obj.url.replace is not a function; [Component] Event Handler Error @ components/feed/feed#(anonymous)
TypeError: obj.url.replace is not a function
    at Object.taro.(anonymous function) [as navigateTo] (http://127.0.0.1:46341/appservice/npm/@tarojs/taro-weapp/dist/index.js:4047:45)
    at Feed.navigateTo (http://127.0.0.1:46341/appservice/components/feed/feed.js:88:23)
    at K.obj.(anonymous function) [as navigateTo] (http://127.0.0.1:46341/appservice/npm/@tarojs/taro-weapp/dist/index.js:3271:36)
    at Object.r.safeCallback (http://127.0.0.1:46341/appservice/__dev__/WAService.js:1:688704)
    at http://127.0.0.1:46341/appservice/__dev__/WAService.js:1:770152
    at f (http://127.0.0.1:46341/appservice/__dev__/WAService.js:1:773307)
    at http://127.0.0.1:46341/appservice/__dev__/WAService.js:1:772581
    at n (http://127.0.0.1:46341/appservice/__dev__/WAService.js:1:278119)
    at e (http://127.0.0.1:46341/appservice/appservice?t=1548644664214:1218:20972)
    at r.registerCallback.t (http://127.0.0.1:46341/appservice/appservice?t=1548644664214:1218:21157)
console.error @ VM152:1
errorReport @ WAService.js:1
thirdErrorReport @ WAService.js:1
(anonymous) @ WAService.js:1
(anonymous) @ WAService.js:1
r.safeCallback @ WAService.js:1
r.call @ WAService.js:1
t.message @ WAService.js:1
r.safeCallback @ WAService.js:1
(anonymous) @ WAService.js:1
f @ WAService.js:1
(anonymous) @ WAService.js:1
n @ WAService.js:1
e @ appservice?t=1548644664214:1218
r.registerCallback.t @ appservice?t=1548644664214:1218
l.forEach.t @ appservice?t=1548644664214:1218
(anonymous) @ appservice?t=1548644664214:1218
s.onmessage @ appservice?t=1548644664214:1218
```

**Comment by W-quan** [comment]
发现`navigateTo(url){}` 里的 `url`是事件对象，传过来的`url`却拿不到

**Comment by W-quan** [comment]
应该是taro框架的问题，升级后正常了
