### ISSUE TITLE
使用cnpm安装时发生错误

### ISSUE THREAD

**Issue by hj24** [NervJS/taro-zhihu-sample#23]
在项目目录下运行cnpm install
```
[npminstall:runscript:error] @tarojs/webpack-runner@1.2.15 › node-sass@4.11.0 scripts.postinstall run "node scripts/build.js" error: Error [RunScriptError]: Run "sh -c node scripts/build.js" error, exit code 1
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/cnpm/node_modules/_runscript@1.4.0@runscript/index.js:96:21)
    at ChildProcess.emit (events.js:196:13)
    at maybeClose (internal/child_process.js:1000:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:5) {
  name: 'RunScriptError',
  stdio: [Object]
}
✖ Install fail! RunScriptError: post install error, please remove node_modules before retry!
Run "sh -c node scripts/build.js" error, exit code 1
RunScriptError: Run "sh -c node scripts/build.js" error, exit code 1
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/cnpm/node_modules/_runscript@1.4.0@runscript/index.js:96:21)
    at ChildProcess.emit (events.js:196:13)
    at maybeClose (internal/child_process.js:1000:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:5)
```

taro版本：1.2.15
cnpm版本：6.1.1

**Comment by hj24** [comment]
@Chen-jj
