### ISSUE TITLE
运行yarn run dev:h5报错

### ISSUE THREAD

**Issue by blueskink** [NervJS/taro-zhihu-sample#8]
开始编译项目 taro_zhihu
创建  发现文件  src/app.js
创建  发现文件  src/app.scss
创建  发现文件  src/index.html
创建  发现文件  src/asset/images/1444983318907-_DSC1826.jpg
创建  发现文件  src/asset/images/24213.jpg
创建  发现文件  src/asset/images/24280.jpg
创建  发现文件  src/asset/images/allread.png
创建  发现文件  src/asset/images/book.png
创建  发现文件  src/asset/images/bottom_tab.gif
创建  发现文件  src/asset/images/burger.png
创建  发现文件  src/asset/images/burger_focus.png
创建  发现文件  src/asset/images/chat.png
创建  发现文件  src/asset/images/chat_focus.png
创建  发现文件  src/asset/images/comment.png
创建  发现文件  src/asset/images/comment2.png
创建  发现文件  src/asset/images/default_avatar.jpeg
创建  发现文件  src/asset/images/discovery.png
创建  发现文件  src/asset/images/discovery_focus.png
创建  发现文件  src/asset/images/draft.png
创建  发现文件  src/asset/images/eye.png
创建  发现文件  src/asset/images/flag.png
创建  发现文件  src/asset/images/good-bad.png
创建  发现文件  src/asset/images/heart2.png
创建  发现文件  src/asset/images/icon1.jpeg
创建  发现文件  src/asset/images/icon8.jpg
创建  发现文件  src/asset/images/icon9.jpeg
创建  发现文件  src/asset/images/index.png
创建  发现文件  src/asset/images/index_focus.png
创建  发现文件  src/asset/images/index_scroll.gif
创建  发现文件  src/asset/images/invite.png
创建  发现文件  src/asset/images/lighting.png
创建  发现文件  src/asset/images/live.png
创建  发现文件  src/asset/images/more.png
创建  发现文件  src/asset/images/navigation.gif
创建  发现文件  src/asset/images/recent.png
创建  发现文件  src/asset/images/ring.png
创建  发现文件  src/asset/images/ring_focus.png
创建  发现文件  src/asset/images/search.png
创建  发现文件  src/asset/images/star.png
创建  发现文件  src/asset/images/star2.png
创建  发现文件  src/asset/images/top_tab.gif
创建  发现文件  src/asset/images/v_discovery.png
创建  发现文件  src/asset/images/v_index.png
创建  发现文件  src/asset/images/write.png
创建  发现文件  src/asset/images/zhi.png
创建  发现文件  src/components/feed/feed.js
创建  发现文件  src/components/feed/feed.scss
创建  发现文件  src/pages/answer/answer.js
创建  发现文件  src/pages/answer/answer.scss
创建  发现文件  src/pages/discovery/discovery.js
创建  发现文件  src/pages/discovery/discovery.scss
创建  发现文件  src/pages/index/.DS_Store
创建  发现文件  src/pages/index/index.js
创建  发现文件  src/pages/index/index.scss
创建  发现文件  src/pages/more/more.js
创建  发现文件  src/pages/more/more.scss
创建  发现文件  src/pages/question/question.js
创建  发现文件  src/pages/question/question.scss

⠋ Compiling...events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:10086
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at Server.setupListenHandle [as _listen2] (net.js:1367:14)
    at listenInCluster (net.js:1408:12)
    at doListen (net.js:1517:7)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! taro_zhihu@1.0.0 build:h5: `taro build --type h5 "--watch"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the taro_zhihu@1.0.0 build:h5 script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by luckyadam** [comment]
`Error: listen EADDRINUSE 127.0.0.1:10086`

端口被占用，换个端口吧
